name: github pages
on:
  push:
    branches: [ github-actions ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: npm i

      - name: generate
        run: npm run generate
        env:
          API_ROOT: ${{ secrets.API_ROOT }}
          DEPLOY_ENV: ${{ secrets.DEPLOY_ENV }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist


